### ISSUE TITLE
Is the light theme contrast correct?

### ISSUE THREAD

**Issue by claytonrcarter** [gt-rios/firefox-syntax#5]
Hi, I've been using this syntax theme for a while w/ the dark theme and been loving it. The light theme works well, too, but feels kind of washed out and low contrast. Is it just me? (Probably!)

Can you confirm that these are intended, or perhaps it's just something whacky in my Atom settings that are throwing this off:

FF 73.0.1 Debugger  
<img width="323" alt="Screen Shot 2020-03-17 at 10 12 14 PM" src="https://user-images.githubusercontent.com/1420419/76918552-eedeff00-689c-11ea-9eb6-0b8d3c506d4f.png">

Atom Beta 1.46.0 w/ UI Theme: One Light & Syntax Theme: Firefox/Default Light
<img width="362" alt="Screen Shot 2020-03-17 at 10 11 52 PM" src="https://user-images.githubusercontent.com/1420419/76918577-0322fc00-689d-11ea-8e92-918d080bab17.png">

Tweaking my stylesheet to display code as bold makes the text stronger, but it still doesn't seem quite right:  
<img width="350" alt="Screen Shot 2020-03-17 at 10 24 39 PM" src="https://user-images.githubusercontent.com/1420419/76919323-ef789500-689e-11ea-9c26-8229aa90031a.png">

Any thoughts? Could it just be a font issue? (In Atom I'm using Fira Code, in FF it's using ...?)

**Comment by gt-rios** [comment]
Hi Clayton! The colors were taken from the devtools' source code so they should be accurate, here's a side by side from my screen for comparison; same font and font size (Fira Mono Regular@11px):

![Screenshot_20200318_174113](https://user-images.githubusercontent.com/17343833/77014383-0cc66580-696a-11ea-9ee2-c5b10d8f32dd.png)

That being said, I do notice a slight difference in contrast which could be explained by the different rendering engines, however, they're not as dramatic as yours. ~~It seems your devtools are also using Fira Code but maybe at a different weight (ie. Medium instead of Regular)? Or a different font size? (I resized my Atom's font size to match the devtools in the screenshot)~~ Edit: Nevermind I'm blind your devtools are using a different font

**Comment by claytonrcarter** [comment]
Funny. I had assumed it was using Fira Code, too, because they look so similar. (I'm using Fira Code in Atom.) Any idea how to figure out what font the dev tools would be using?

I've got nothing concrete to add here, except that my current temporary workaround is to add this to my stylesheet:
```css
atom-text-editor {
  // for light theme
  div.line when(luma(@syntax-background-color) > 50%) {
    font-weight: 600;
  }
}
```

It's a little aggressive, b/c the Atom rendering engine seems to make everything >= 600 to just be full on bold (I couldn't find a setting that was semi-bold anything), but it definitely helps w/ the contrast issue.

Thanks for your help!

**Comment by gt-rios** [comment]
@claytonrcarter looks like your devtools font is Menlo:
https://dxr.mozilla.org/mozilla-central/source/devtools/client/themes/common.css#35
You can change your Atom font to Menlo or, alternatively, you could try using the Medium variant of Fira Code (font-weight: 500) if you have that installed, there's no Semi-bold (font-weight: 600) for Fira Code afaik.

**Comment by claytonrcarter** [comment]
I looked into this again and it turns out that I was using an old version of Fira Code (v2). The current version (v3) was just released last month and [added a semi-bold variant](https://github.com/tonsky/FiraCode/issues/987). Something else about the v2->v3 change must have changed for me, because after upgrade the `600` weight was suddenly too bold. I was able to alter my snippet above to use `font-weight: 500` and it looks much better now. Thanks again!
